<form method="POST">
    @csrf
    <div class="form-group">
        <label>Nama</label>
        <input type="text" class="form-control" id="form-nama" name="nama" required value="{{is_object($item) ? ($item->nama ?? '') : ''}}" onkeyup="generateKodeFromNama()">
        <small class="text-muted">Kode akan otomatis dibuat dari nama</small>
    </div>

    <div class="form-group">
        <label>Kode</label>
        <input type="text" class="form-control" id="form-kode" name="kode" required value="{{is_object($item) ? ($item->kode ?? '') : ''}}">
        <small class="text-muted">Dapat diedit manual jika diperlukan</small>
    </div>

    <button class="btn btn-primary mt-3">Submit</button>

</form>

<script>
function generateKodeFromNama() {
    var nama = document.getElementById('form-nama').value.trim();
    var kodeInput = document.getElementById('form-kode');
    
    // Only auto-generate if kode field is empty or was auto-generated
    if (nama && (!kodeInput.value || kodeInput.dataset.autoGenerated === 'true')) {
        var words = nama.split(' ').filter(function(word) { return word.trim().length > 0; });
        var kodeParts = [];
        
        words.forEach(function(word) {
            word = word.toUpperCase().trim();
            if (word.length >= 3) {
                kodeParts.push(word.substring(0, 3));
            } else {
                // Use the word as-is if it's 2 letters or less (no padding)
                kodeParts.push(word);
            }
        });
        
        var generatedKode = kodeParts.join('-');
        kodeInput.value = generatedKode;
        kodeInput.dataset.autoGenerated = 'true';
    }
}

// Initialize on page load
document.addEventListener('DOMContentLoaded', function() {
    var namaInput = document.getElementById('form-nama');
    var kodeInput = document.getElementById('form-kode');
    
    // If editing and kode exists, mark as not auto-generated (user can still edit)
    if (kodeInput.value) {
        kodeInput.dataset.autoGenerated = 'false';
    } else {
        // If new, generate kode from nama if nama exists
        if (namaInput.value) {
            generateKodeFromNama();
        }
    }
    
    // Reset auto-generated flag when user manually edits kode
    kodeInput.addEventListener('input', function() {
        this.dataset.autoGenerated = 'false';
    });
});
</script>

